In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int) # convert categorical into numerical dataset so that a model can be created

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns # get the column headers only

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [7]:
#Get the independent/Input dataset alone
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent # Display the independant dataset

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
#Get the dependent/output dataset alone
dependent=dataset[["charges"]]

In [10]:
# split the dataset into test set and training set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

## Preprocessing for standardization by standardization formula(x-Mean)/Sigma where x is the i/p

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [23]:
# Train the model using the training dataset
import  sklearn.model_selection as GSCV
from sklearn.svm import SVR
param_grid = {'kernel':['linear', 'rbf', 'poly', 'sigmoid'],'C':[10,1,5000,4000]}

In [24]:
grid =  GSCV.GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,y_train)
re = grid.cv_results_
pd.DataFrame.from_dict(re)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\prabha_7589\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.066650,0.010588,0.005971,0.001444,10,linear,"{'C': 10, 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,7
1,0.053158,0.013256,0.019940,0.002289,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,11
2,0.033544,0.004776,0.005539,0.000911,10,poly,"{'C': 10, 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,8
3,0.049526,0.003139,0.008421,0.000789,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,9
4,0.031508,0.003207,0.005331,0.001279,1,linear,"{'C': 1, 'kernel': 'linear'}",0.016409,0.033832,-0.083831,-0.078347,-0.084332,-0.039254,0.052891,10
5,0.034901,0.001600,0.019622,0.000799,1,rbf,"{'C': 1, 'kernel': 'rbf'}",-0.037143,-0.033009,-0.143600,-0.134313,-0.137861,-0.097185,0.050815,14
6,0.027464,0.002057,0.005023,0.001050,1,poly,"{'C': 1, 'kernel': 'poly'}",-0.031902,-0.027215,-0.136794,-0.126911,-0.132027,-0.090970,0.050261,12
7,0.041639,0.002052,0.007811,0.000933,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",-0.032208,-0.026296,-0.136623,-0.129505,-0.131761,-0.091279,0.050731,13
8,0.096349,0.011183,0.004619,0.000389,5000,linear,"{'C': 5000, 'kernel': 'linear'}",0.660277,0.583489,0.697919,0.528640,0.655731,0.625211,0.060851,6
9,0.066624,0.005903,0.019840,0.001972,5000,rbf,"{'C': 5000, 'kernel': 'rbf'}",0.839143,0.801308,0.824177,0.820269,0.748315,0.806642,0.031559,3
10,0.286873,0.142566,0.007451,0.003952,5000,poly,"{'C': 5000, 'kernel': 'poly'}",0.849180,0.804663,0.817089,0.804538,0.762291,0.807552,0.027892,1
11,0.056790,0.000888,0.009916,0.003120,5000,sigmoid,"{'C': 5000, 'kernel': 'sigmoid'}",-5.587576,-6.464665,-5.733393,-7.528981,-4.041185,-5.871160,1.144450,16
12,0.113256,0.022861,0.006739,0.001068,4000,linear,"{'C': 4000, 'kernel': 'linear'}",0.660277,0.583489,0.697920,0.529117,0.655735,0.625308,0.060700,5
13,0.091490,0.009443,0.026750,0.004212,4000,rbf,"{'C': 4000, 'kernel': 'rbf'}",0.838637,0.795748,0.820474,0.815572,0.747543,0.803595,0.031176,4
14,0.203818,0.081836,0.006406,0.003101,4000,poly,"{'C': 4000, 'kernel': 'poly'}",0.847935,0.804701,0.817607,0.806030,0.760519,0.807358,0.028122,2
15,0.048224,0.007716,0.008041,0.001278,4000,sigmoid,"{'C': 4000, 'kernel': 'sigmoid'}",-3.534876,-3.710653,-3.355452,-4.463480,-2.226415,-3.458175,0.722226,15

In [25]:

#testdata run againt the pediction. 
grid_pred=grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_pred)
print("The r2 score value for best parameter {}:".format(grid.best_params_),grid.best_score_)

grid_pred=grid.predict()

The r2 score value for best parameter {'C': 5000, 'kernel': 'poly'}: 0.8075520280389711

In [22]:
grid_pred

array([ 9921.40420198,  8710.96844365, 47815.71339319, 12580.50859973,
       10499.75888479,  4603.25134588,  1483.52793895, 11161.9035753 ,
        7407.93108902,  5303.43333137,  6927.44496459, 10142.46172164,
        7622.09295016,  4844.31142141, 25386.7953456 , 10758.47057359,
       12489.46037154,  3440.51634428,  6493.57644704, 24052.72020622,
       25778.0328377 , 12170.06432854,  9736.74670363, 31005.30592626,
        1899.55958409,  4830.06197389,  4425.97181002,  7965.96003291,
        4344.7724023 ,  8322.65846578,  7898.89954384, 50982.70513485,
       13013.92482456, 10246.59728037, 13110.83612134,  4096.81514159,
        8731.73619273, 36037.70061794, 36349.10489535,  2043.91386117,
        5935.73727687,  3235.98588839, 27386.99528339, 44342.33903865,
       33410.03312195,  3128.35417034, 10763.95904299,  7006.69567483,
        4695.49858919, 12195.98515298,  2717.43274096,  2940.238462  ,
       30979.14759882, 43722.67549316, 11831.56109752,  3170.20738393,
        2759.32202167,  8635.20609112,  9761.21344179, 13155.36604706,
        1124.69385558, 35286.29722037, 13960.53448017,  9825.93550959,
       10182.65600131, 10063.169366  , 22695.80212032, 34038.72449755,
        3009.23703296,  7924.36098961, 13099.17244155, 11742.88315043,
       19154.63407097, 13897.23170612, 12950.95556076, 12712.59717762,
        7684.73557774,  8048.98026377, 25086.1018332 , 44480.88390498,
       11134.19842682, 55640.23360866,  1851.72128667,  7796.03370415,
       40188.36238365, 22596.80437051,  3903.79825334,  2652.80610706,
       12550.4063165 , 36642.29545074,  6158.01477898, 10245.90881951,
        3114.51418798,  8630.07623536,  4426.57190659,  5057.30390822,
       37036.3969788 , 32897.68249307,  5312.46426507, 10586.85819445,
        2071.807308  ,  5622.47830186,  4665.83813811, 38202.53222895,
       29554.37848696,  3675.81763974, 11104.87232767,  3765.55379224,
       11360.035894  , 40556.43194985, 12558.21336982,  4780.70741179,
        9001.17623743, 24001.78108155, 52071.0804337 ,  7526.82900998,
        2044.57930505,  8627.21195831, 12532.27958406,  9160.52834977,
       40430.78096658, 10780.77196937, 14340.74160045,  5219.05861877,
        7886.92390823,  4992.34415994, 27398.60881291, 21988.99335507,
       50796.15542191,  1761.05254765,  8362.0838675 ,  1821.3805329 ,
        6394.76499706,  9258.84205105, 33763.32397599, 32196.87049454,
       25457.94392724, 10282.72901428, 22166.99986218,  2659.41196421,
        2010.89803822, 10302.07135579,  9599.86959133,  9874.86443339,
        5065.19099237, 14334.28783235, 12812.88314257,  3422.9173999 ,
        1179.37267055, 10729.13843493,  6367.61354107, 43324.82167448,
        9607.83325007,  1666.75053423,  2457.35750929,  6862.30468   ,
        2568.11803553,  1641.68972678, 10759.07411197,  9887.54929963,
        4460.50838866, 12995.0158782 , 12805.15838026,  9691.81861135,
        4904.45002574,  4138.56460773, 12153.94442767,  5754.50289969,
        4374.34128896,  1656.11698944,  4144.49558965,  4194.91257791,
        8108.45643269,  2359.25336929,  4400.47166897,  4364.63276449,
        4276.28399251,  6455.7244017 , 33761.93766068,   867.36186881,
       10758.53638704,  6692.11990052, 10972.34088988,  2924.87727183,
        5675.1764742 , 30924.80505277,  1840.6360773 ,  2571.65199772,
       14323.24607828,  9852.79720642, 38196.5386568 ,  4125.71271886,
        5910.45956813, 26332.13982374,  2558.95530487,  2168.69446016,
        6261.64656603,  6368.74354234,  4685.66088022,  4389.43810843,
       10919.71765302, 42242.39905091, 11792.7291905 , 22295.43107576,
        4519.60031754, 43303.37398185,  3537.02366241,  9201.39110525,
        6303.94615787,  1019.95126883,  8681.29600755, 13451.93044974,
        5018.03215525,  2687.48066319,  6725.43970985,  2219.35790116,
        6435.43331785,  5372.25365451, 13997.82307704,  7356.49824449,
        6629.87792155,  7787.09371357,  8520.95181923,  3104.85776465,
       11841.46843017, 13909.89685303, 12250.40168803, 12052.43951473,
        7266.08523791,  2383.78886674,   947.76886746,  8206.07864803,
       12238.2985181 ,  3399.40442246,  5056.64740711,  7287.36480879,
        9017.02246197, 27320.34748246,  5980.5154415 , 11263.7786651 ,
        5907.38971406, 28982.7624835 ,  7761.35435062,  7245.96036056,
        8223.34647498, 10260.1681147 ,  2653.71799762,  7716.87705122,
        2451.53749218,  6832.04650761, 27298.18537502, 35790.08181639,
        4276.53645686,  3701.15013757,  1509.89844124,   902.14314594,
        7851.39765937,  1670.33888552,  4322.15449544,  3951.43400251,
        9333.82726828, 29859.83806419, 39383.70852263, 14493.1398433 ,
        6724.72458993, 10959.52901614, 41787.48483653,  9209.78490109,
       36487.07543461,  1082.76003477, 35228.43486259,  5273.99020445,
       12359.08817448,  3840.07524855, 38238.3309223 ,  5545.45421058,
        9529.05995126, 10490.59030706,  2189.66646204, 13148.60269791,
       11937.16490214,  4445.40299006, 12200.81433922,  1528.99492924,
        6156.19977245,  3595.78975746,  9660.83056846, 25681.65282593,
        3244.68459545,   865.59118032,  2320.34872518, 42924.83778104,
        9033.84420715,  4873.4017252 , 11807.7820174 , 11265.90168402,
       29191.94728227,  6854.70500911,  5310.95462084,  8575.27550594,
        1175.75485012,  2584.64325678,  8270.91248884, 21194.37815128,
       13474.24867977,  2380.46829386,  3580.17265136,  8808.13229116,
        9196.2125033 , 11452.43782712, 26534.16117476,  6408.10335524,
       13894.14113857,  1759.04150211,  5787.14069235,  4417.93995743,
        8407.41972969,  2026.74046085,  6585.90711715, 47108.27933671,
        3421.88812912,  4010.25576217,  1802.18878413,  8522.49449981,
        3988.13644013, 12280.70908076, 38678.47075694, 17412.89687952,
        8970.51828123, 43509.81174753, 12546.10041415,  4532.10950436,
        9593.1768885 ,  3710.43540832, 32644.82755552,  5011.19445468,
       13602.01445951,  1766.10539679, 16998.44475323,  3395.88645582,
       26462.29918504,  6161.49187916,  2210.48053688, 42804.19139372,
        5536.2428579 ,  5464.99371885, 32789.14889862,  1170.07239293,
        8245.94219694,  2233.63889083, 12667.97120213,  3961.6767041 ,
        5743.07532502,  5091.94288949, 41997.87898164,  8830.96500573,
       31421.71168603, 33789.54939587,  5981.06921197,  8935.12677635,
        1106.9673502 ,  3517.95322962,  2596.26376156,  8756.17105328,
       40220.95710062, 11317.36327118,  1727.47615949, 12035.12647894,
        2307.17437637,  7681.44345145,  3965.40821465,  2113.83308629,
        3333.92250212, 31661.51195517,  7387.83177597,  1676.72377812,
       41109.31518686, 10970.36387498, 39746.76703986, 11758.28715596,
        4742.22588427,  2343.39618686,  1949.89402583, 10121.2206087 ,
        5274.13749802,  1572.22656772, 10239.1859015 ,  7391.17607384,
        6292.33438967,  4109.54466898,  2592.29545394, 38139.69480967,
        1618.03631983,  9235.78594014,  1674.36500963,  7535.27243822,
       10597.09988668,  3990.75747141, 17167.08250797, 10245.23826669,
       14681.39604038, 13710.57256433])

In [159]:
#If the core is near to 1 then it is good model
r_score

0.03930714378274347

In [131]:
import pickle
filename="finalized_model_SVM.sav"
pickle.dump(regressor,open(filename,'wb'))

In [107]:
loaded_model=pickle.load(open("finalized_model_SVM.sav",'rb'))
result=loaded_model.predict([[1234,345,4565,1,0]])

In [108]:
result

array([108734.5006363])